---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CF_PROJECT}-data
  namespace: ${CF_PROJECT}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  selector:
    matchLabels:
      mount: "localshop-data"
