apiVersion: v1
kind: Service
metadata:
  name: ${KUBE_WEB_LABEL}
  namespace: ${CF_PROJECT}
  labels:
    app.kubernetes.io/name: ${CF_PROJECT}
    app.kubernetes.io/component: ${KUBE_WEB_LABEL}
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: ${CF_PROJECT}
    app.kubernetes.io/component: ${KUBE_WEB_LABEL}
  sessionAffinity: None
  type: ClusterIP
