apiVersion: v1
kind: Secret
metadata:
  name: ${CF_PROJECT}-auth
  namespace: ${CF_PROJECT}
type: Opaque
data:
  AUTH_LDAP_BIND_DN: {{ '${AUTH_LDAP_BIND_DN}' | b64encode }}
  AUTH_LDAP_BIND_PASSWORD: {{ '${AUTH_LDAP_BIND_PASSWORD}' | b64encode }}
  AUTH_LDAP_SERVER_URI: {{ '${AUTH_LDAP_SERVER_URI}' | b64encode }}
  AUTH_LDAP_USER_DN_TEMPLATE: {{ '${AUTH_LDAP_USER_DN_TEMPLATE}' | b64encode }}
  AUTH_LDAP_USER_SEARCH_BASE: {{ '${AUTH_LDAP_USER_SEARCH_BASE}' | b64encode }}
