---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localshop-data
  labels:
    mount: localshop-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  nfs:
    server: prod-home-nfs
    path: /srv/data/docker-pypi-web-data
