version: '3.3'
services:
    app:
      build: ..
      image: ${DOCKER_IMAGE}
      command: uwsgi --http 0.0.0.0:8000 --module localshop.wsgi --master --die-on-term
      volumes:
        - ${PYPI_MOUNT_PATH}:/media
      networks:
        - servicenet

    db:
      image: postgres:9.6
      volumes:
        - ${PYPI_DB_MOUNT_PATH}:/var/lib/postgresql/data
      networks:
        - servicenet

    worker:
      image: ${DOCKER_IMAGE}
      entrypoint:
        localshop
      command: celery worker -B -E
      volumes:
        - ${PYPI_MOUNT_PATH}:/media
      networks:
        - servicenet

    service_proxy:
      image: registry.osslabs.net/service-proxy:0.1.1
      restart: always
      labels:
        com.openslate.service_ip: ${SERVICE_IP}/24
      networks:
        - hostnet


networks:
    hostnet:
      external:
        name: host

    servicenet:
      driver: overlay
      ipam:
        driver: default
        config:
          - subnet: ${DOCKER_SUBNET}
