services:
    db:
      environment:
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD

    web:
      environment:
        - DJANGO_SECRET_KEY
        - DATABASE_URL
        - DJANGO_MEDIA_ROOT
        - DJANGO_DEBUG
        - AUTH_LDAP_BIND_PASSWORD
        - AUTH_LDAP_SERVER_URI
        - AUTH_LDAP_BIND_DN
        - AUTH_LDAP_USER_SEARCH_BASE
        - AUTH_LDAP_USER_DN_TEMPLATE

    worker:
      environment:
        - DJANGO_SECRET_KEY
        - DATABASE_URL
        - DJANGO_MEDIA_ROOT

    service_proxy:
      environment:
        - SERVICE_IP
        - SERVICE_PORT
        - VAULT_ADDR
        - VAULT_CERTIFICATE_PATH=/v1/secret/ssl/star.osslabs.net
        - VAULT_TOKEN
