version: '3.4'
services:
    app:
      build: ..
      image: ${DOCKER_IMAGE}
      command: uwsgi --http 0.0.0.0:8000 --module localshop.wsgi --master --die-on-term
      volumes:
        - ${PYPI_MOUNT_PATH}:/media

    worker:
      image: ${DOCKER_IMAGE}
      entrypoint:
        localshop
      command: celery worker -B -E
      volumes:
        - ${PYPI_MOUNT_PATH}:/media
