services:
    app:
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.role == worker
          preferences:
            - spread: node.id
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 256M
            cpus: '0.1'
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 20
          window: 120s

    postgres:
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.role == worker
          preferences:
            - spread: node.id
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 256M
            cpus: '0.1'
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 20
          window: 120s

    worker:
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.role == worker
          preferences:
            - spread: node.id
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 256M
            cpus: '0.1'
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 20
          window: 120s

    service_proxy:
      image: registry.osslabs.net/service-proxy:0.1.1
      restart: always
      labels:
        com.openslate.service_ip: ${SERVICE_IP}/24
      networks:
        - hostnet
      deploy:
        placement:
          constraints:
            - node.role == worker
        replicas: 1
        resources:
          limits:
            memory: 128M
          reservations:
            memory: 64M
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 20
          window: 120s
