services:
  postgres:
    image: postgres:9.6
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ${PYPI_DB_MOUNT_PATH}:/var/lib/postgresql/data


volumes:
  ${PYPI_DB_MOUNT_PATH}:
    driver: local
